-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 20:45:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema guiedani
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guiedani
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guiedani` DEFAULT CHARACTER SET utf8 ;
USE `guiedani` ;

-- -----------------------------------------------------
-- Table `guiedani`.`presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`presentation` (
  `id_presentation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_presentation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`origin` (
  `id_origin` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_origin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`roast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`roast` (
  `id_roast` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_roast`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`products` (
  `id_product` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(2) UNSIGNED NULL,
  `img_1` VARCHAR(300) NULL,
  `img_2` VARCHAR(300) NULL,
  `img_3` VARCHAR(300) NULL,
  `img_4` VARCHAR(300) NULL,
  `description` VARCHAR(300) NULL,
  `id_presentation` INT UNSIGNED NULL,
  `id_origin` INT UNSIGNED NULL,
  `id_roast` INT UNSIGNED NULL,
  `grams` INT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_products_presentation_idx` (`id_presentation` ASC) VISIBLE,
  INDEX `fk_products_origin1_idx` (`id_origin` ASC) VISIBLE,
  INDEX `fk_products_roast1_idx` (`id_roast` ASC) VISIBLE,
  CONSTRAINT `fk_products_presentation`
    FOREIGN KEY (`id_presentation`)
    REFERENCES `guiedani`.`presentation` (`id_presentation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_origin1`
    FOREIGN KEY (`id_origin`)
    REFERENCES `guiedani`.`origin` (`id_origin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_roast1`
    FOREIGN KEY (`id_roast`)
    REFERENCES `guiedani`.`roast` (`id_roast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `count` INT UNSIGNED NOT NULL,
  `id_product` INT NULL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_stock_products2_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_stock_products2`
    FOREIGN KEY (`id_product`)
    REFERENCES `guiedani`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`orders` (
  `id_order` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id_order`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`costumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`costumers` (
  `id_costumer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_costumer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`order_item` (
  `id_order_item` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT UNSIGNED NOT NULL,
  `id_product` INT NULL,
  `total` DECIMAL(2) NOT NULL,
  `id_order` INT NULL,
  PRIMARY KEY (`id_order_item`),
  INDEX `fk_order_item_products1_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_order_item_order1_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `guiedani`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`id_order`)
    REFERENCES `guiedani`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`costumer_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`costumer_has_orders` (
  `id_costumer` INT UNSIGNED NOT NULL,
  `orders_id_order` INT UNSIGNED NOT NULL,
  INDEX `fk_costumer_has_orders_orders1_idx` (`orders_id_order` ASC) VISIBLE,
  INDEX `fk_costumer_has_orders_costumer1_idx` (`id_costumer` ASC) VISIBLE,
  PRIMARY KEY (`orders_id_order`, `id_costumer`),
  CONSTRAINT `fk_costumer_has_orders_costumer1`
    FOREIGN KEY (`id_costumer`)
    REFERENCES `guiedani`.`costumers` (`id_costumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costumer_has_orders_orders1`
    FOREIGN KEY (`orders_id_order`)
    REFERENCES `guiedani`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guiedani`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guiedani`.`stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `count` INT UNSIGNED NOT NULL,
  `id_product` INT NULL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_stock_products2_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_stock_products2`
    FOREIGN KEY (`id_product`)
    REFERENCES `guiedani`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
